apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mockapi
  template:
    metadata:
      labels:
        app: mockapi
    spec:
      containers:
        - name: sandbox
          image: ""
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3080
          env:
            - name: MONGO_URI
              value: ""
        - name: harborlabs
